await PortableWorldExportSmoke.RunAsync();
Sim04WorldStateSmoke.Run();
Sim04DiagnosticSmoke.Run();
Sim05OperationLifecycleSmoke.Run();
await Sim05DurableOperationSmoke.RunAsync();
await Sim05CoordinatorSmoke.RunAsync();
await Sim06StepCoordinatorSmoke.RunAsync();
await Sim06ConfigBoundarySmoke.RunAsync();
await Sim06DependencyDagSmoke.RunAsync();
await Sim06DurableFinalizeSmoke.RunAsync();
await Sim06DurableFinalizationSmoke.RunAsync();
Sim07SpatialSmoke.Run();
Sim07EnvironmentSmoke.Run();
Sim08MotionPathSmoke.Run();
Sim08CollisionSmoke.Run();
Sim08CrossOwnerIntentSmoke.Run();
Sim08HandoffSmoke.Run();
Sim08PrimitiveCollisionSmoke.Run();
Sim08SequentialImpulseSmoke.Run();
await Sim08StateRuntimeSmoke.RunAsync();
Sim09ResidentCoreSmoke.Run();
await Sim09RuntimeGateSmoke.RunAsync();
Sim10MarketLedgerSmoke.Run();
await Sim10RuntimeGateSmoke.RunAsync();
Sim11GovernanceLawSmoke.Run();

Console.WriteLine("SIM-01..SIM-11 component smoke tests passed through Governance/Security deterministic law foundation.");
